### ISSUE TITLE
Compilation speed

### ISSUE THREAD

**Issue by azev77** [s-broda/ARCHModels.jl#63]
I wonder if compilation speed can be improved.

Suppose I load a Julia package `ACME` with one function `f(x,y)`. 
The first time I use `f(x,y)` is usually slow for a given set of argument types. But it is usually much faster after that. 
```julia
using ACME
f(1,2)   # usually slow
f(1,2)   # much faster
f(2,5)   # equally fast 
f(2.0,5) # slow again, bc it prev compiled f(Int,Int), now it must compile f(Float,Int)
f(2.0,5) # faster
```
When I run: 
```julia
using ARCHModels
@time selectmodel(TGARCH,BG96,minlags=1,maxlags=1)
@time selectmodel(TGARCH,BG96,minlags=1,maxlags=1)
@time selectmodel(TGARCH,BG96,minlags=2,maxlags=2)
@time selectmodel(TGARCH,BG96,minlags=2,maxlags=2)
@time selectmodel(TGARCH,BG96,minlags=3,maxlags=3)
@time selectmodel(TGARCH,BG96,minlags=3,maxlags=3)
@time selectmodel(TGARCH,BG96,minlags=1,maxlags=3)
@time selectmodel(TGARCH,BG96,minlags=1,maxlags=3)
```
The compilation time becomes slow every time I change the number of lags, even though the types of each argument is the same:
```julia

julia> 
  5.247489 seconds (18.78 M allocations: 927.158 MiB, 6.23% gc time)
  0.005477 seconds (2.68 k allocations: 212.594 KiB)
  1.121684 seconds (3.90 M allocations: 183.957 MiB, 4.12% gc time)
  0.012191 seconds (10.07 k allocations: 1.081 MiB)
  1.179797 seconds (4.01 M allocations: 188.687 MiB, 5.05% gc time)
  0.018243 seconds (10.68 k allocations: 1.540 MiB)
 25.694519 seconds (90.85 M allocations: 4.179 GiB, 3.69% gc time)
  0.098000 seconds (282.74 k allocations: 32.622 MiB)

julia> 
```
Can this be improved?

**Comment by s-broda** [comment]
I've replied to your question on [discourse](https://discourse.julialang.org/t/another-post-on-package-compilation-time/42015/7?u=s-broda). In addition, note that recompilation only happens when you estimate a model that you haven't before. If you start you benchmarking with the largest collection of models, then all the other calls will be fast after that:

```julia
julia> @time selectmodel(TGARCH,BG96,minlags=1,maxlags=3);
 29.091732 seconds (97.49 M allocations: 4.918 GiB, 7.94% gc time)

julia> @time selectmodel(TGARCH,BG96,minlags=3,maxlags=3);
  0.015270 seconds (9.74 k allocations: 1.527 MiB)

julia> @time selectmodel(TGARCH,BG96,minlags=1, maxlags=1);
  0.005761 seconds (2.57 k allocations: 225.125 KiB)

julia> @time selectmodel(TGARCH,BG96,minlags=1, maxlags=2);
  0.020432 seconds (72.11 k allocations: 7.541 MiB)
```

etc. Of course you wouldn't want to do that, it's just to explain what happens under the hood. As mentioned on discourse, I've benchmarked this against the alternative of not parametrizing the types, and it doesn't really help. So I'll close this because there's not much we can do, other than waiting for general compile time improvements.

**Comment by s-broda** [comment]
I'll reopen this. It seems it's possible to avoid recompilation by not parametrizing the types, and padding the coefficient vector to a fixed length.
