### ISSUE TITLE
(G)ARCHModels.jl

### ISSUE THREAD

**Issue by pkofod** [s-broda/ARCHModels.jl#7]
Hi @s-broda !

Not sure if you want to make it that verbose, but you could consider calling your package ARCHModels.jl or GARCHModels.jl to allow exporting ARCH.  Since you're exporting things like `ARCHModels.jl` this would actually follow the "old" (I don't think they're active anymore) pkg name guidelines. Could also just be `ARCHs.jl`

**Comment by s-broda** [comment]
Hi Patrick

Yes, I've thought about that. I kind of do like the brevity of ARCH.jl though :) One other option would be UGARCH.jl (U for univariate). I think that's what Matlab used to call it.
Cheers
Simon

**Comment by pkofod** [comment]
I totally get the brevity argument. The only problem is, that it seems odd to have multivariate GARCH models in a completely separate package. 

Would it be totally off to consider the ARCH-content as part of a larger TimeSeries package? I know there's an unmaintained TimeSeries.jl package, but something like it.

I'm interested because I've been thinking for a while that time series econometrics is really a field in economics/econometrics where it would be quite easy to attract people to Julia.

**Comment by s-broda** [comment]
Sorry for the late reply. Yes, I think you are right that having multivariate models separately might be a bit awkward, so renaming the package to ARCHModels might be the most sensible course of action; though really, I don't view the inability to export ARCH as a big issue, because hardly anyone uses a pure ARCH (except maybe for teaching). 

I think that a TimeSeries package might be a bit to broad. I do hope that the package will become part of the JuliaStats Github org ones it matures a bit more.

**Comment by pkofod** [comment]
> Sorry for the late reply

No worries! I'll be following the package, and hopefully I can only contribute at some point.

**Comment by s-broda** [comment]
Package renamed and soon to have its first release :)

**Comment by pkofod** [comment]
That's awesome!
